[package]
name = "hello_rust"
version = "0.1.0"
authors = ["sage <5129310+vzhougm@user.noreply.gitee.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
